name: opencnpj
description: A Dart client library for the OpenCNPJ API.
version: 0.2.0
repository: https://github.com/cristianocosta/opencnpj

environment:
  sdk: ^3.8.0

dependencies:
  http: ^1.6.0
  json_annotation: ^4.9.0
  equatable: ^2.0.7
  cpf_cnpj_validator: ^2.0.0

dev_dependencies:
  build_runner: ^2.7.1
  json_serializable: ^6.11.2
  mocktail: ^1.0.4
  lints: ^6.0.0
  test: ^1.25.15