name: opencnpj
description: A Dart client library for the OpenCNPJ API.
version: 0.1.0
repository: https://github.com/cristianocosta/opencnpj

environment:
  sdk: ^3.8.0

dependencies:
  http: ^1.1.0
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  cpf_cnpj_validator: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  lints: ^2.1.1
  test: ^1.24.0