name: opencnpj_server_example
description: A simple Shelf server example for OpenCNPJ.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  json_annotation: ^4.9.0
  opencnpj:
    path: ../..

dev_dependencies:
  build_runner: ^2.4.0
  json_serializable: ^6.7.0
  lints: ^3.0.0
